name: Deploy on Koyeb

on:
  push:
    branches:
      - module-2-exercise

jobs:
  deployment:
    if: github.ref == 'refs/heads/module-2-exercise'
    runs-on: ubuntu-latest

    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: '${{ secrets.KOYEB_API_TOKEN }}'

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          git-branch: ${{ github.head_ref }}
          app-name: 'expressjs-pr-${{ github.head_ref }}'
          service-name: ${{ github.head_ref }}
          service-ports: '8080:http'
          service-routes: '/:8080'